// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetLinkByCode(ctx context.Context, code string) (Link, error)
	GetLinkById(ctx context.Context, id int64) (Link, error)
	GetLinks(ctx context.Context, arg GetLinksParams) ([]Link, error)
	GetLinksByUser(ctx context.Context, arg GetLinksByUserParams) ([]Link, error)
	GetUser(ctx context.Context, usernameoremail string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	ToggleStatus(ctx context.Context, arg ToggleStatusParams) (Link, error)
	UpdateCode(ctx context.Context, arg UpdateCodeParams) (Link, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
